{
 "title": "Backbone Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(confluent_kafka_server_retained_bytes, kafka_id)"
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": "label_values(confluent_kafka_server_retained_bytes, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Informações importantes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusters",
     "type": "text",
     "description": "Identificação dos clusters",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
     "options": {
      "content": "| Ambiente | Cluster Id |\n|----------|------------|\n| DEV | XXXXXX |\n| HML | XXXXXX |\n| PRD | XXXXXX |"
     }
    },
    { "title": "Lista de service-account", "type": "text", "description": "Lista de services-account", "gridPos": { "h": 7, "w": 10, "x": 3, "y": 1 } }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Percentual de utilização do servidor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_load_percent{kafka_id=~\"$cluster\"}*100",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Quantidade de partições",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_partition_count{kafka_id=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Média de conexões ativas",
   "type": "stat",
   "description": "Média de conexões ativas",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(confluent_kafka_server_active_connection_count{kafka_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Quantidade de conexões ativas autenticadas por user / service-account",
   "type": "graph",
   "description": "Quantidade de conexões ativas autenticadas por principal_id ( Filtrando mais do que 10 conexões ativas )\n\nprincipal_id is the authentication principal (Confluent Cloud User or Service Account)",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_active_connection_count{kafka_id=~\"$cluster\"}) by (principal_id) >= 10",
     "legendFormat": "{{principal_id}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Consumer Group Lag Offsets",
   "type": "gauge",
   "description": "Quantidade de offsets pendentes de leitura por consumer group id não considerando consumer group que começa com _confluent-ksql ou connect-snk",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_consumer_lag_offsets{kafka_id=~\"$cluster\",consumer_group_id!~\"^(_confluent-ksql.*)|(connect-snk.*)$\"}) by (consumer_group_id) > 0",
     "legendFormat": "{{consumer_group_id}}"
    }
   ]
  },
  {
   "title": "Mensagens recebidas por tópico",
   "type": "bargauge",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_received_records{kafka_id=~\"$cluster\",topic!~\"^(_confluent-ksql.*)|(connect-snk.*)$\",topic=~\"$topic\"}) > 0",
     "legendFormat": "[{{kafka_id}}] {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes recebidos por tópico",
   "type": "bargauge",
   "description": "The delta count of bytes of the customer's data received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_received_bytes{kafka_id=~\"$cluster\",topic!~\"^(_confluent-ksql.*)|(connect-snk.*)$\",topic=~\"$topic\"}) > 0",
     "legendFormat": "[{{kafka_id}}] {{topic}}"
    }
   ]
  }
 ]
}